<a href="https://colab.research.google.com/github/RudravMahure/numpy/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
# single dimension array
a=np.array([1,2,3])
print(a)
# two dimensional array
print()
a=np.array([[1,2,3],[4,5,6]])
print(a)


[1 2 3]

[[1 2 3]
 [4 5 6]]


In [12]:
#print array of zeros
a=np.zeros(3)
print(a)
print()
#print array of ones
a=np.ones(4)
print(a)
print()
#create empty array
a=np.empty(10)
print(a)
print()

[0. 0. 0.]

[1. 1. 1. 1.]

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323
 4.0e-323 4.4e-323]



In [18]:
# create an array of 0 to 9
a=np.arange(10)
print(a)

print()

# np.arange(first name , last name , difference)
a=np.arange(3,9,3)
print()
a=np.arange(3,10,3)
print(a)

print()

a=np.linspace(2,10,5)
print(a)

[0 1 2 3 4 5 6 7 8 9]


[3 6 9]

[ 2.  4.  6.  8. 10.]


In [27]:
#sort and concatination of arrays
a=np.array([1,2,465,324,254,76,1234,654,3743])
b=np.array([5,37432,8673,237,3942])

#concatenation of two strieng
print(np.concatenate((a,b)))
c=np.concatenate((a,b))

#sorting of  string
c=np.sort(c)
print()
print(c)

#this type of concatention is only perform on same dimension of array
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[9,10,11,12],[13,14,15,16]])

print()
#axis=0 means row wise arrangement of arrays
print(np.concatenate((a,b),axis=0))

print()
#axis=0 means column wise arrangement of arrays
print(np.concatenate((a,b),axis=1))

[    1     2   465   324   254    76  1234   654  3743     5 37432  8673
   237  3942]

[    1     2     5    76   237   254   324   465   654  1234  3743  3942
  8673 37432]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]
