<a href="https://colab.research.google.com/github/RudravMahure/numpy/blob/main/numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Accessing elements in numpy

Elements can be accessed using indices inside square brackets, [ ]. NumPy allows you to use both positive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array.


In [2]:
import numpy as np

In [7]:
#Accessing Elements
#numpy supports both negative and positive indexing
x=np.array([1,2,3,4,5])
print("Array:")
print("x= ",x)
print()

#Positive indexing
print('First element is ',x[0],' and second element is ',x[1])

#Negative indesxing
print('Last elemet of array is ',x[-1],' second last element is ',x[-2])

Array:
x=  [1 2 3 4 5]

First element is  1  and second element is  2
Last elemet of array is  5  second last element is  4


Modifying ndarrays:
Now let's see how we can change the elements in rank 1 ndarrays. We do this by accessing the element we want to change and then using the = sign to assign the new value:

In [ ]:
#Modifing elements in array
arr=np.array([1,2,3,4,5])
print('Array before updarting is ',x)
print()
arr[4]=10
print('Array after updating is ',x)


In [9]:
#Creating an array of size 3x3

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array:- ',arr)
print()
print('arr[0,0]= ',arr[0,0])
print('arr[1,2]= ',arr[1,2])
print('arr[2,2]= ',arr[2,2])

#arr[row,element in that row]
#in terms of 2D array arr[row,column]

Array:-  [[1 2 3]
 [4 5 6]
 [7 8 9]]

X[0,0]=  1
x[1,2]=  6
x[2,2]=  9



Similarly, we can also access and modify specific elements of rank 2 ndarrays. To access elements in rank 2 ndarrays we need to provide 2 indices in the form [row, column]. Let's see some examples



In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Before Changes:- ')
print(arr)
print()

arr[0,0]=90
arr[1][1]=20

print('After Changes:- ')
print(arr)

Before Changes:- 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After Changes:- 
[[90  2  3]
 [ 4 20  6]
 [ 7  8  9]]


Adding and Deleting elements:

Now, let's take a look at how we can add and delete elements from ndarrays. We can delete elements using the np.delete(ndarray, elements, axis) function. This function deletes the given list of elements from the given ndarray along the specified axis. For rank 1 ndarrays the axis keyword is not required. For rank 2 ndarrays, axis = 0 is used to select rows, and axis = 1 is used to select columns. Let's see some examples:

In [15]:
#Create an 1D array
x=([1,2,3,4,5])
#Create an 2D array
y=([[1,2,3],[4,5,6],[7,8,9]])
print('x')
print(x)
print('y')
print(y)
#Operations on 1D array
#first and last element of array is deleted
x=np.delete(x,[0,4])
print('Deletion in X')
print(x)

#Operation on 2D array
#Deletion of row
y=np.delete(y,2,axis=0)
print('Deletion of last row from the y ')
print(y)

#Deletion of column
y=np.delete(y,[0,1],axis=1)
print('Deletion of first and second column from the y')
print(y)

x
[1, 2, 3, 4, 5]
y
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Deletion in X
[2 3 4]
Deletion of last row from the y 
[[1 2 3]
 [4 5 6]]
Deletion of first and second column from the y
[[3]
 [6]]


We can append values to ndarrays using the np.append(ndarray, elements, axis) function. This function appends the given list of elements to ndarray along the specified axis. Let's see some examples:

In [20]:
#Create a 1 rank array
x=np.array([1,2,3,4,5])

#Create a 2D array
y=np.array([[1,2,3],[4,5,6]])

print('X:-')
print(x)
print('Y:-')
print(y)

#Append elements in array
#Elemets add at the last , we can add single element or array
x=np.append(x,[6])

x=np.append(x,[7,8])

print('Modified X')
print(x)

#append elements in array
#append the row
y=np.append(y,[[7,8,9]],axis=0)
print('Modified y')
print(y)
#append column
y=np.append(y,[[10],[11],[12]],axis=1)
print('After Modification y')
print(y)

X:-
[1 2 3 4 5]
Y:-
[[1 2 3]
 [4 5 6]]
Modified X
[1 2 3 4 5 6 7 8]
Modified y
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Modification y
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


Now let's see now how we can insert values to ndarrays. We can insert values to ndarrays using the np.insert(ndarray, index, elements, axis) function. This function inserts the given list of elements to ndarray right before the given index along the specified axis. Let's see some examples:

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x.
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)

NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. It is important to note that in order to stack ndarrays, the shape of the ndarrays must match. Let's see some examples:

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2])

# We create a rank 2 ndarray
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y.
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)

Slicing ndarrays:
As we mentioned earlier, in addition to being able to access individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]
The first method is used to select elements between the start and end indices. The second method is used to select all elements from the start index till the last index. The third method is used to select all elements from the first index till the end index. We should note that in methods one and three, the end index is excluded. We should also note that since ndarrays can be multidimensional, when doing slicing you usually have to specify a slice for each dimension of the array.

We will now see some examples of how to use the above methods to select different subsets of a rank 2 ndarray.

In [ ]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

'''
X =
     0  1  2  3  4
0 [[ 0  1  2  3  4]
1 [ 5  6  7  8  9]
2 [10 11 12 13 14]
3 [15 16 17 18 19]]

'''
# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5:2]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)
#1:4 2:5
#1: 2:5
# :3,2:5:2
# 2,:

Notice that when we selected all the elements in the 3rd column, variable q above, the slice returned a rank 1 ndarray instead of a rank 2 ndarray. However, slicing X in a slightly different way, variable R above, we can actually get a rank 2 ndarray instead.

It is important to note that when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable. This is one feature that often causes confusion for beginners. Therefore, we will look at this in a bit more detail.

In the above examples, when we make assignments, such as:

Z = X[1:4,2:5]
the slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. This means that if you make changes in Z you will be in effect changing the elements in X as well. Let's see this with an example:

In [ ]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

'''
X =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
'''

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 4th columns
Z = X[1:4,2:5]

# We print Z
print()
print('Z = \n', Z)
print()

# We change the last element in Z to 555
Z[2,2] = 555

X[2,2]=90
# We print X
print()
print('X = \n', X)
print()

print()
print(Z)