<a href="https://colab.research.google.com/github/RudravMahure/numpy/blob/main/numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [7]:

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array = ",arr)
print()

print("Shape / Dimension of an array = ",arr.shape)
print("Total elements in array = ",arr.size)
print("Type of elements in array = ",arr.dtype)
print("Class of array = ",type(arr))

array =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape / Dimension of an array =  (3, 3)
Total elements in array =  9
Type of elements in array =  int64
Class of array =  <class 'numpy.ndarray'>


In [11]:
#while creating an array if we use dtype as specifie the type of data must be store in it,while only that type of data is store is irrespective of what we save
a=np.array([1.0,2.43,4.34],dtype=np.int64)
print("A array= ",a)
print()
print("The of elements in array: ",a.dtype)

A array=  [1 2 4]

The of elements in array:  int64


In [14]:
#Create an 1D array
arr=np.array([1,2,3,4,5])
#Save the array arr in directory my_arr
np.save('my_arr',arr)
print("arr :",arr)

arr : [1 2 3 4 5]


In [16]:
#load the elements from directory to array
x=np.load('my_arr.npy')
print("x: ",x)
print()
print("Number of elements in directory: ",x.size)
print("Shape of directory: ",x.shape)
print("Type of elements in array: ",x.dtype)

x:  [1 2 3 4 5]

Number of elements in directory:  5
Shape of directory:  (5,)
Type of elements in array:  int64


In [19]:
X = np.eye(10,dtype=np.int8)
print(X)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [20]:
x=np.arange(4,10,2)
print("X: ",x)

X:  [4 6 8]


In [24]:
x=np.random.random((2,3))
print("X: ",x)

X:  [[0.86550705 0.56803083 0.21502873]
 [0.86253049 0.01910563 0.99486658]]


In [26]:
x=np.random.randint(10,20,size=(3,3))
print("X: ",x)

X:  [[10 16 16]
 [18 15 15]
 [16 15 15]]


In [31]:
x=np.array([1,2,3,4,5])
print("Original X: ",x)
x=np.delete(x,[0,4])
print("Modified X: ",x)

Original X:  [1 2 3 4 5]
Modified X:  [2 3 4]


In [ ]:
# We create a rank 1 ndarray
import numpy as np
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])


# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)     # (3,3)
w2 = np.delete(Y, [0,2], axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)


print()
print(w2)
print()
# We print v
print()
print('v = \n', v)

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

# We print v
print()
print('v = \n', v)

# We print q
print()
print('q = \n', q)

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x.
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,10,axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)


# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2])

# We create a rank 2 ndarray
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y.
w = np.hstack((x.reshape(2,1),Y))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)