<a href="https://colab.research.google.com/github/RudravMahure/numpy/blob/main/numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Boolean Indexing:**

There are many situations in which we don't know the indices of the elements we want to select. For example, suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us select elements using logical arguments instead of explicit indices. Let's see some examples:

In [1]:
import numpy as np

In [11]:
#RANDOM:- random function is use to select random elements
#RANDINT:- this function is used to give values between ranges (start,end,number of elements)
#RESHAPE:- this function is used to reshape the matrix/array
arr=np.random.randint(0,30,100).reshape(10,10)

#Print the array
print()
print('Print Array:-',arr)
print()

#it give boolean value if greater than 10 true or false
print((arr>10))
#Print the account need
print('Elements greater than 20:-',arr[arr>20])
print('Elements greater than 10 and less than 20:-',arr[(arr>10)&(arr<20)])
print('Elements less than 20:-',arr[arr<20])
print('Elements less than 10 or greater than 20:-',arr[(arr<10)|(arr>20)])


print(arr>10)


Print Array:- [[20 19  9 28 15 14 12 12 28 20]
 [19  3  6  9 28 21 23 29  6 17]
 [21 26 13 25  0  4 20 29  2  7]
 [ 7 12  8 18  0 29 19 24 25  4]
 [24 25 27 28  3  3 25 12  7 16]
 [12 18  1 25 12 10 16 29 15  1]
 [ 4 21 23 29  2  1 25 24 24  5]
 [29 21 27 12  9 20 11 13 26 17]
 [26 28  6 24 28  5 22 27 20 13]
 [13  7  7  9 11  7 26 27 22 25]]

[[ True  True False  True  True  True  True  True  True  True]
 [ True False False False  True  True  True  True False  True]
 [ True  True  True  True False False  True  True False False]
 [False  True False  True False  True  True  True  True False]
 [ True  True  True  True False False  True  True False  True]
 [ True  True False  True  True False  True  True  True False]
 [False  True  True  True False False  True  True  True False]
 [ True  True  True  True False  True  True  True  True  True]
 [ True  True False  True  True False  True  True  True  True]
 [ True False False False  True False  True  True  True  True]]
Elements greater than 

**Set Operations:**

In addition to Boolean Indexing NumPy also allows for set operations. This useful when comparing ndarrays, for example, to find common elements between two ndarrays. Let's see some examples:

In [16]:
#Creating to array
x=np.array([1,2,3,4,5])
y=np.array([4,5,6,7,8,9])

#Creating 1D array
print('X:-')
print(x)
print("Y:-")
print(y)

#Operations on sets
print('Intersection of sets:- ',np.intersect1d(x,y))
print('Union of sets:-',np.union1d(x,y))
print('Difference of sets:-',np.setdiff1d(x,y))

X:-
[1 2 3 4 5]
Y:-
[4 5 6 7 8 9]
Intersection of sets:-  [4 5]
Union of sets:- [1 2 3 4 5 6 7 8 9]
Difference of sets:- [1 2 3]


**Sort():**


We can also sort ndarrays in NumPy. We will learn how to use the np.sort() function to sort rank 1 and rank 2 ndarrays in different ways. Like with other functions we saw before, the sort function can also be used as a method. However, there is a big difference on how the data is stored in memory in this case.

When np.sort() is used as a function, it sorts the ndrrays out of place, meaning, that it doesn't change the original ndarray being sorted.
However, when you use sort as a method, ndarray.sort() sorts the ndarray in place, meaning, that the original array will be changed to the sorted one.

In [22]:
arr=np.random.randint(0,20,50)

print('Original array')
print('X:-',arr)
print()

print("Sorted array using np.sort() function:- ",np.sort(arr))

print("After Sorting array:- ",arr)

#using ndarray.sort() the orginial array is sort permanently



Original array
X:- [16 17  6  9  2  6 17  7 19  9 13 14  1  5 19  4 16  5  2  6  1  3 11  0
  7  2 14  9 19 11 16  2  7 14 14 10  8  8  1 17 10 19 17  6  7 14  2 19
  3 19]

Sorted array using np.sort() function:-  [ 0  1  1  1  2  2  2  2  2  3  3  4  5  5  6  6  6  6  7  7  7  7  8  8
  9  9  9 10 10 11 11 13 14 14 14 14 14 16 16 16 17 17 17 17 19 19 19 19
 19 19]
After Sorting array:-  [16 17  6  9  2  6 17  7 19  9 13 14  1  5 19  4 16  5  2  6  1  3 11  0
  7  2 14  9 19 11 16  2  7 14 14 10  8  8  1 17 10 19 17  6  7 14  2 19
  3 19]


In [27]:
#Create an array
arr=np.random.randint(0,10,15)

print("Orignial array:-",arr)
#using unique we only keep unique value
#return_counts gives the count of numbers
print(np.sort(np.unique(arr)))
print(np.unique(arr,return_counts=True))
print(np.unique(arr))

Orignial array:- [8 2 4 4 1 7 4 9 8 6 9 5 6 7 1]
[1 2 4 5 6 7 8 9]
(array([1, 2, 4, 5, 6, 7, 8, 9]), array([2, 1, 3, 1, 2, 2, 2, 2]))
[1 2 4 5 6 7 8 9]


When sorting rank 2 ndarrays, we need to specify to the np.sort() function whether we are sorting by rows or columns. This is done by using the axis keyword. Let's see some examples:

In [30]:
#create an array
arr=np.random.randint(0,10,size=(5,5))
print("Array:- ",arr)

#We sort the columns of X and print the sorted array
print()
print("Sorting using column:-",np.sort(arr,axis=0))

# We sort the rows of X and print the sorted array
print()
print("Sorting using row:-",np.sort(arr,axis=1))

Array:-  [[3 2 1 3 0]
 [2 8 3 7 5]
 [9 7 9 3 1]
 [0 2 7 6 8]
 [7 9 4 8 0]]

Sorting using column:- [[0 2 1 3 0]
 [2 2 3 3 0]
 [3 7 4 6 1]
 [7 8 7 7 5]
 [9 9 9 8 8]]

Sorting using row:- [[0 1 2 3 3]
 [2 3 5 7 8]
 [1 3 7 9 9]
 [0 2 6 7 8]
 [0 4 7 8 9]]


In [33]:
arr1=np.empty(shape=(2,2))
print(x)
print(x.dtype)
for i in range(2):
  for j in range(2):
    arr1[i,j]=input()
print()
print(arr1)

[1 2 3 4 5]
int64
12
25
32
11

[[12. 25.]
 [32. 11.]]


**Arithmtic Operations:**

Let's start by doing element-wise addition, subtraction, multiplication, and division, between ndarrays. To do this, NumPy provides a functional approach, where we use functions such as np.add(), or by using arithmetic symbols, such as +, that resembles more how we write mathematical equations. Both forms will do the same operation, the only difference is that if you use the function approach, the functions usually have options that you can tweak using keywords. It is important to note that when performing element-wise operations, the shapes of the ndarrays being operated on, must have the same shape or be broadcastable. We'll explain more about this later in this lesson. Let's start by performing element-wise arithmetic operations on rank 1 ndarrays:

In [ ]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))     #np.dot(x,y)  for matrix multiplication
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

# print(x*[5])
# print(x+[5])
print(x+5)
print(x*5)


We can also perform the same element-wise arithmetic operations on rank 2 ndarrays. Again, remember that in order to do these operations the shapes of the ndarrays being operated on, must have the same shape or be broadcastable.

In [ ]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))
print()
print('np.dot(X,Y)',np.dot(X,Y))

print("deterinant of matrix",np.linalg.det(X))

# p*q  q*r => p*r

We can also apply mathematical functions, such as sqrt(x), to all elements of an ndarray at once.

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,3)) # We raise all elements to the power of 2
print()

Another great feature of NumPy is that it has a wide variety of statistical functions. Statistical functions provide us with statistical information about the elements in an ndarray. Let's see some examples:

In [34]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))
print()


arr:- [[1 2 3]
 [4 5 6]
 [7 8 9]]


Finally, let's see how NumPy can perform arithmetics between a single numbers and all the elements of an ndarray without the use of complicated loops.

In [ ]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)
print()